name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install TFX CLI
        run: npm install -g tfx-cli
      
      - name: Build extension
        run: npm run build
      
      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Extract changelog for this version
        id: changelog
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          # Extract changelog section for this version
          if [ -f "marketplace/changelog.md" ]; then
            CHANGELOG=$(awk "/^## \[$VERSION\]/{flag=1;next}/^## \[/{flag=0}flag" marketplace/changelog.md || echo "See [CHANGELOG.md](marketplace/changelog.md) for details.")
            echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGELOG" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "CHANGELOG=See [CHANGELOG.md](marketplace/changelog.md) for details." >> $GITHUB_OUTPUT
          fi
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.TAG }}
          body: |
            # Azure DevOps Mermaid ${{ steps.get_version.outputs.TAG }}
            
            ## What's Changed
            
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ## Installation
            
            Install from the [Azure DevOps Marketplace](https://marketplace.visualstudio.com/items?itemName=jramos.azure-devops-mermaid)
            
            Or download the `.vsix` file below and install manually.
            
            ---
            
            **Full Changelog**: https://github.com/javiramos1/azure-devops-mermaid/blob/main/marketplace/changelog.md
          files: |
            *.vsix
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish to Azure DevOps Marketplace
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          if [ -n "${{ secrets.AZURE_DEVOPS_PAT }}" ]; then
            echo "Publishing to Azure DevOps Marketplace..."
            tfx extension publish --token ${{ secrets.AZURE_DEVOPS_PAT }} --vsix *.vsix
            echo "✅ Published to marketplace!"
          else
            echo "⚠️  AZURE_DEVOPS_PAT secret not set. Skipping marketplace publish."
            echo "To enable automatic publishing, add your Azure DevOps PAT as a repository secret."
          fi
        continue-on-error: true
